#!/usr/bin/bash
#
# machine: system settings

dracut_live_conf="$(ls /etc/dracut.conf.d/*livecd.conf 2> /dev/null)"
if [ ! -z "$dracut_live_conf" ]; then
    echo "Avoid to add live components to initramfs"
    rm ${dracut_live_conf} -f
fi

system_product_name="$(dmidecode --string system-product-name)"
if [ "$system_product_name" == "HP 250 G8 Notebook PC" ]; then
    # When closing laptop lid airplane mode comes on and won't go off:
    # https://bugzilla.redhat.com/show_bug.cgi?id=1628353
    # https://askubuntu.com/questions/965595/why-does-airplane-mode-keep-toggling-on-my-hp-laptop-in-ubuntu-18-04
    echo "HP 250 G8 - Fix airplane mode when closing laptop lid"
    setkeycodes e057 240 e058 240
fi
