#!/usr/bin/sh
#
# Configure the Calamares installer
#

# Create liveuser desktop folder
mkdir -p  /home/liveuser/Desktop

# Adjust installer launcher
cp -a /usr/share/applications/calamares.desktop.orig /home/liveuser/Desktop/livesys-install.desktop
desktop-file-edit --set-key=Exec --set-value="$(find /usr/lib -name kdesu) calamares" \
/home/liveuser/Desktop/livesys-install.desktop

# Make installer icon executable to disable KDE security warning
chmod +x /home/liveuser/Desktop/livesys-install.desktop

# Add installer icon to local applications
mkdir -p  /home/liveuser/.local/share/applications
ln -s /home/liveuser/Desktop/livesys-install.desktop /home/liveuser/.local/share/applications

# Replace Discover icon in KDE taskmanager
sed -i -e 's/applications:org.kde.discover.desktop/applications:livesys-install.desktop/' \
/usr/share/plasma/plasmoids/org.kde.plasma.taskmanager/contents/config/main.xml    

# Patch squashfs path to match live media
sed -i -e 's/source: ".*"/source: "\/dev\/mapper\/live-base"/' \
-e 's/sourcefs: "squashfs"/sourcefs: "ext4"/' \
/etc/calamares/modules/unpackfs.conf

# Override final apt sources configuration (it's not necessary to modify it, already set)
cp /usr/local/libexec/livesys/sources-final /usr/sbin/sources-final

# Remove original installer icon (because it's a duplicate)
rm /usr/share/applications/install-debian.desktop -f