#!/usr/bin/sh
#
# graphical-setup: desktop settings for liveuser

# Set up auto login for live user
if [ -f /etc/sddm.conf ]; then
    sed -i 's/^#User=.*/User=liveuser/' /etc/sddm.conf
    sed -i "s/^#Session=.*/Session=plasma.desktop/" /etc/sddm.conf
else
cat > /etc/sddm.conf << SDDM_EOF
[Autologin]
User=liveuser
Session=plasma.desktop
SDDM_EOF
fi

# Disable plasma-discover-notifier
desktop-file-edit --set-key=Hidden --set-value=true /etc/xdg/autostart/org.kde.discover.notifier.desktop

# Replace Discover icon in taskmanager with the installer icon
sed -i -e 's/applications:org.kde.discover.desktop/applications:livesys-install.desktop/' \
 /usr/share/plasma/plasmoids/org.kde.plasma.taskmanager/contents/config/main.xml

# Disable automount of 'known' devices
# https://bugzilla.redhat.com/show_bug.cgi?id=2073708
cat > /home/liveuser/.config/kded_device_automounterrc << AUTOMOUNTER_EOF
[General]
AutomountEnabled=false
AutomountOnLogin=false
AutomountOnPlugin=false
AUTOMOUNTER_EOF
