#!/usr/bin/sh

## Add liveuser user with no passwd
useradd --comment "Live System User" --create-home --shell /usr/bin/bash liveuser
passwd -d liveuser
adduser liveuser sudo
adduser liveuser audio
adduser liveuser video
adduser liveuser adm

# Set up auto login for live user
if [ -f /etc/sddm.conf ]; then
    sed -i 's/^#User=.*/User=liveuser/' /etc/sddm.conf
    sed -i "s/^#Session=.*/Session=plasma.desktop/" /etc/sddm.conf
else
cat > /etc/sddm.conf << SDDM_EOF
[Autologin]
User=liveuser
Session=plasma.desktop
SDDM_EOF
fi
